##--------------------------------------------------------------------------------------##
##---------------------------------- PROD PROFILE --------------------------------------##
##--------------------------------------------------------------------------------------##
##---------------------------------- Server Config ---------------------------------------
quarkus.http.port=3232
quarkus.http.ssl-port=9494
quarkus.application.name=API-IMAGE
quarkus.application.version=1.0
quarkus.resteasy.gzip.enabled=true
quarkus.http.cors=true
quarkus.openapi-generator.codegen.spec.openapi_yml.model-name-prefix=QuarkusOpenApiGenerator
##--------------------------------------------------------------------------------------##
##---------------------------------- DESENV PROFILE ------------------------------------##
##--------------------------------------------------------------------------------------##
# #----------------------------------- Database config  ------------------------------------
%dev.quarkus.datasource.username=api-image
%dev.quarkus.datasource.password=senha
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5458/postgres
%dev.quarkus.hibernate-orm.database.generation=update


quarkus.http.limits.max-body-size=1000M
quarkus.http.limits.max-form-attribute-size=1000M